name: FE - Deploy static content to Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pages: write

# Allow one concurrent deployment
concurrency:
  cancel-in-progress: true
  group: "pages"

jobs:
  # Single deploy job since we're just deploying
  deploy:
    defaults:
      run:
        working-directory: ./frontend
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@maglifter'
      - run: npm ci
      - run: npm run build-all

      - name: Create artifacts directory
        shell: bash
        run: |
          mkdir artifacts
          cp index.html artifacts
          mv dist artifacts

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'frontend/artifacts'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
